version: "3.9"
services:
  
  jupyter:
    build: 
     context: .
     dockerfile: Dockerfile

    ports:
      - "9000:8888"

    volumes:
      - ../:/home/work

    environment:
      HOME: "/home/work/"

    user: 1000:1000

    restart: always
    working_dir: /home/work
    runtime: nvidia
    container_name: StatisticalStudy


    command: poetry run jupyter-lab --no-browser --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token='' --NotebookApp.notebook_dir='/home/work'
    #command: sleep 4000




