from gcr.io/kaggle-gpu-images/python

#RUN pip install jupyterlab_code_formatter/ pip install black isort

# R install
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9 \
   && add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/' \
   && apt update \ 
   && apt install r-base -y 

