version: "3.9"
services:
  
  jupyter:
    build: 
     context: .
     dockerfile: Dockerfile

    ports:
      - "9000:8888"

    volumes:
     - /home/ryuichi/staticstics:/home/work

    environment:
      HOME: "/home/work/"

    restart: always


    command: jupyter-lab --no-browser --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token='' --NotebookApp.notebook_dir='/home/work'




